name: Build PE Parser

on:
  workflow_dispatch:  
  push:
    tags: ['v*']     

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        
    - name: Build Windows executable
      run: |
        # Create a simple placeholder script for testing
        echo "print('PE Parser would run here')" > pe_parser.py
        pyinstaller --onefile --name pe-parser-windows --console pe_parser.py
        
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4 
      with:
        name: pe-parser-windows
        path: dist/pe-parser-windows.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install pyinstaller
        
    - name: Build Linux executable
      run: |
        # Create a simple placeholder script for testing
        echo "print('PE Parser would run here')" > pe_parser.py
        pyinstaller --onefile --name pe-parser-linux --console pe_parser.py
        
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4 
      with:
        name: pe-parser-linux
        path: dist/pe-parser-linux

  create-release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download Windows artifact
      uses: actions/download-artifact@v4  
      with:
        name: pe-parser-windows
        path: dist
        
    - name: Download Linux artifact
      uses: actions/download-artifact@v4 
      with:
        name: pe-parser-linux
        path: dist
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/pe-parser-windows.exe
          dist/pe-parser-linux